# general
seed: 42

# data
datapath_train: '/home/rmiccini/stanford_mir2/data/nsynth-train'
datapath_valid: '/home/rmiccini/stanford_mir2/data/nsynth-valid'
datapath_test:  '/home/rmiccini/stanford_mir2/data/nsynth-test'
sr: 16000
duration: 4
batch_size: 32
num_workers: 0
n_mels: null
n_fft: 512
win_length: 512
hop_length: 256
data_mean: './data_mean_nomel.pt'  # for overall normalization use -59.4373 (db)
data_std:  './data_std_nomel.pt'  # for overall normalization use 32.1454 (db)
db_range: [-90, -5]

# training
start_lr: 0.0001
epochs: 100
val_every: 10
log_pictures: false

# model
model_type: 'leakyrelu_nomel'  # also pix_shuffle & pix_shuffle2
fc_hidden1: 512
fc_hidden2: 1024
fc_hidden3: 4096  # 896 for pix_shuffle2
lspace_size: 256

# loss
loss_type: 'classes' # also vae
rec_weight: 1.0
kld_weight: 0.01
ce_weight: 0.05
kld_exp: 1.2
