# general
seed: 42

# data
datapath_train: '/home/rmiccini/stanford_mir2/data/nsynth-train'
datapath_valid: '/home/rmiccini/stanford_mir2/data/nsynth-valid'
datapath_test:  '/home/rmiccini/stanford_mir2/data/nsynth-test'
sr: 16000
duration: 4
batch_size: 32
num_workers: 4
n_mels: 80
data_mean: 'datapoint'  # for overall normalization use -41.5759 (db)
data_std:  'datapoint'  # for overall normalization use 38.5646 (db)

# training
start_lr: 0.0001
epochs: 100
val_every: 10

# model
model_type: 'leakyrelu'  # also pix_shuffle & pix_shuffle2
fc_hidden1: 512
fc_hidden2: 1024
fc_hidden3: 4096  # 896 for pix_shuffle2
lspace_size: 256

# loss
loss_type: 'classes' # also vae
rec_weight: 1.0
kld_weight: 0.01
ce_weight: 0.05
kld_exp: 1.2
